import type { ProductCardProps } from '~/components/marketplace/ProductCard';
import type { VendorCardProps } from '~/components/marketplace/VendorCard';
import type { Database } from "./database.types"

type storeListing = Database['public']['Tables']['store_listings']['Row'];

export const storeListings: storeListing[] = [
  {
    id: '1',
    store_id: 'vendor_1',
    title: 'Sample Product',
    description: 'This is a sample product description.',
    price: 1999,
    image_url: 'https://example.com/sample-product.jpg',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true
  },
  {
    id: '2',
    store_id: 'techstore',
    title: 'Wireless Headphones',
    description: 'High-quality wireless headphones with noise cancellation.',
    price: 5999,
    image_url: 'https://example.com/wireless-headphones.jpg',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true
  },
  {
    id: '3',
    store_id: 'healthylife',
    title: 'Organic Green Tea',
    description: 'Premium organic green tea leaves sourced from Japan.',
    price: 1249,
    image_url: 'https://example.com/green-tea.jpg',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true
  },
  {
    id: '4',
    store_id: 'bookworld',
    title: 'Classic Novel Set',
    description: 'A collection of timeless literary classics.',
    price: 2999,
    image_url: 'https://example.com/novel-set.jpg',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true
  },
  {
    id: '5',
    store_id: 'fitgear',
    title: 'Fitness Tracker',
    description: 'Advanced fitness tracker with heart rate monitoring.',
    price: 7999,
    image_url: 'https://example.com/fitness-tracker.jpg',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true
  },
  {
    id: '6',
    store_id: 'artisanbites',
    title: 'Gourmet Chocolate Box',
    description: 'Hand-crafted artisan chocolates in assorted flavors.',
    price: 2499,
    image_url: 'https://example.com/chocolate-box.jpg',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true
  },
  {
    id: '7',
    store_id: 'greenearth',
    title: 'Bamboo Utensil Set',
    description: 'Eco-friendly reusable bamboo utensils for on-the-go meals.',
    price: 1599,
    image_url: 'https://example.com/bamboo-utensils.jpg',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true
  },
  {
    id: '8',
    store_id: 'bytebrew',
    title: 'Signature Blend Coffee',
    description: 'Medium roast specialty coffee with notes of caramel and hazelnut.',
    price: 1899,
    image_url: 'https://example.com/signature-coffee.jpg',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true
  },
  {
    id: '9',
    store_id: 'urbanthreads',
    title: 'Vintage Denim Jacket',
    description: 'Classic vintage-style denim jacket with modern fit.',
    price: 8999,
    image_url: 'https://example.com/denim-jacket.jpg',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true
  },
  {
    id: '10',
    store_id: 'techstore',
    title: 'Portable Charger',
    description: '20000mAh portable power bank with fast charging support.',
    price: 3499,
    image_url: 'https://example.com/portable-charger.jpg',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_active: true
  }
]

export const stockVendors: VendorCardProps[] = [
  {
    id: 'techstore',
    name: 'TechStore',
    tagline: 'Cutting-edge gadgets and accessories',
    rating: 4.8,
    reviewCount: 1320,
    location: 'San Francisco, CA',
    category: 'Electronics',
    logoUrl: 'https://example.com/vendors/techstore-logo.png',
    coverUrl: 'https://example.com/vendors/techstore-cover.jpg',
    verified: true,
  },
  {
    id: 'healthylife',
    name: 'HealthyLife Market',
    tagline: 'Clean ingredients for a balanced lifestyle',
    rating: 4.6,
    reviewCount: 980,
    location: 'Austin, TX',
    category: 'Groceries',
    logoUrl: 'https://example.com/vendors/healthylife-logo.png',
    coverUrl: 'https://example.com/vendors/healthylife-cover.jpg',
    verified: false,
  },
  {
    id: 'bookworld',
    name: 'BookWorld',
    tagline: 'Stories, knowledge, and inspiration',
    rating: 4.9,
    reviewCount: 2140,
    location: 'Portland, OR',
    category: 'Books',
    logoUrl: 'https://example.com/vendors/bookworld-logo.png',
    coverUrl: 'https://example.com/vendors/bookworld-cover.jpg',
    verified: true,
  },
  {
    id: 'fitgear',
    name: 'FitGear',
    tagline: 'Performance wearables and fitness tech',
    rating: 4.7,
    reviewCount: 1665,
    location: 'Denver, CO',
    category: 'Fitness',
    logoUrl: 'https://example.com/vendors/fitgear-logo.png',
    coverUrl: 'https://example.com/vendors/fitgear-cover.jpg',
    verified: true,
  },
  {
    id: 'artisanbites',
    name: 'Artisan Bites',
    tagline: 'Small batch snacks crafted with care',
    rating: 4.5,
    reviewCount: 740,
    location: 'Brooklyn, NY',
    category: 'Snacks',
    logoUrl: 'https://example.com/vendors/artisanbites-logo.png',
    coverUrl: 'https://example.com/vendors/artisanbites-cover.jpg',
    verified: false,
  },
  {
    id: 'greenearth',
    name: 'GreenEarth Goods',
    tagline: 'Eco-conscious products for sustainable living',
    rating: 4.4,
    reviewCount: 520,
    location: 'Seattle, WA',
    category: 'Home',
    logoUrl: 'https://example.com/vendors/greenearth-logo.png',
    coverUrl: 'https://example.com/vendors/greenearth-cover.jpg',
    verified: false,
  },
  {
    id: 'bytebrew',
    name: 'ByteBrew Coffee',
    tagline: 'Tech-inspired specialty coffee blends',
    rating: 4.9,
    reviewCount: 1885,
    location: 'Boston, MA',
    category: 'Coffee',
    logoUrl: 'https://example.com/vendors/bytebrew-logo.png',
    coverUrl: 'https://example.com/vendors/bytebrew-cover.jpg',
    verified: true,
  },
  {
    id: 'urbanthreads',
    name: 'Urban Threads',
    tagline: 'Streetwear staples with a modern edge',
    rating: 4.3,
    reviewCount: 610,
    location: 'Los Angeles, CA',
    category: 'Fashion',
    logoUrl: 'https://example.com/vendors/urbanthreads-logo.png',
    coverUrl: 'https://example.com/vendors/urbanthreads-cover.jpg',
    verified: false,
  },
];

export const stockProducts: ProductCardProps[] = [
  {
    id: '2',
    name: 'Wireless Headphones',
    storeName: 'TechStore',
    price: 59.99,
    imageUrl: 'https://example.com/wireless-headphones.jpg',
  },
  {
    id: '3',
    name: 'Organic Green Tea',
    storeName: 'HealthyLife',
    price: 12.49,
    imageUrl: 'https://example.com/green-tea.jpg',
  },
  {
    id: '4',
    name: 'Classic Novel Set',
    storeName: 'BookWorld',
    price: 29.99,
    imageUrl: 'https://example.com/novel-set.jpg',
  },
  {
    id: '5',
    name: 'Fitness Tracker',
    storeName: 'FitGear',
    price: 79.99,
    imageUrl: 'https://example.com/fitness-tracker.jpg',
  },
  {
    id: '6',
    name: 'Gourmet Chocolate Box',
    storeName: 'Artisan Bites',
    price: 24.99,
    imageUrl: 'https://example.com/chocolate-box.jpg',
  },
  {
    id: '7',
    name: 'Bamboo Utensil Set',
    storeName: 'GreenEarth Goods',
    price: 15.99,
    imageUrl: 'https://example.com/bamboo-utensils.jpg',
  },
  {
    id: '8',
    name: 'Signature Blend Coffee',
    storeName: 'ByteBrew Coffee',
    price: 18.99,
    imageUrl: 'https://example.com/signature-coffee.jpg',
  },
  {
    id: '9',
    name: 'Vintage Denim Jacket',
    storeName: 'Urban Threads',
    price: 89.99,
    imageUrl: 'https://example.com/denim-jacket.jpg',
  },
  {
    id: '10',
    name: 'Portable Charger',
    storeName: 'TechStore',
    price: 34.99,
    imageUrl: 'https://example.com/portable-charger.jpg',
  },
  {
    id: '1',
    name: 'Sample Product',
    storeName: 'Sample Store',
    price: 19.99,
    imageUrl: 'https://example.com/sample-product.jpg',
  },
]

export const featuredProducts: ProductCardProps[] = [
    {
      id: '2',
      name: 'Wireless Headphones',
      storeName: 'TechStore',
      price: 59.99,
    },
    {
      id: '3',
      name: 'Organic Green Tea',
      storeName: 'HealthyLife',
      price: 12.49,
    },
    {
      id: '4',
      name: 'Classic Novel Set',
      storeName: 'BookWorld',
      price: 29.99,
    },
    {
      id: '5',
      name: 'Fitness Tracker',
      storeName: 'FitGear',
      price: 79.99,
    }
  ]